extends: 
  - eslint:recommended
  - prettier
plugins:
  - prettier
parser: "esprima"
parserOptions:
  ecmaVersion: 6
env:
  browser: true
  node: true
rules: 
  import/no-commonjs: "off"
  import/no-nodejs-modules: "off"
  no-console: "off"
  prettier/prettier: "error"
