---
language: node_js
node_js:
- node
before_install:
- pushd ./server && npm install                                                                        && popd
- pushd ./client && npm install                                                                        && popd
script:
- pushd ./server && ./node_modules/.bin/eslint app.js                                                  && popd
- pushd ./client && ./node_modules/.bin/browserify js/sovereign.js > js/browserify/sovereign-bundle.js && popd
- pushd ./client && ./node_modules/.bin/eslint js/*.js                                                 && popd
